runtime: nodejs12
env: standard
instance_class: F1
handlers:
- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto
env_variables:
  DATABASE_URL: postgres://postgres:a1N5D9R3e5@@35.199.97.251/QuiosqueMassagem
  DB_USER: postgres
  DB_PASS: a1N5D9R3e5@
  DB_NAME: QuiosqueMassagem
  DB_SOCKET_PATH: /cloudsql
  CLOUD_SQL_CONNECTION_NAME: quiosquemassagem:southamerica-east1:quiosquemassagem
  JWT_SECRET: APMDevQuisoqueMassagem
  JWT_EXPIRES_IN: 99999h
  USER_MD5_SECRET: APMDevQuisoqueMassagem
  CORS_URLS_LIST: ['http://localhost:8080', 'undefined', 'https://editor.swagger.io', 'https://quiosquemassagem.rj.r.appspot.com', undefined]
  RESPONSE_ENCODE_KEY: JOOJ123WAWA
  FRONT_END_KEY: WAWA123JOOJ
  GCLOUD_STORAGE_BUCKET: quiosquemassagem.appspot.com
beta_settings:
  cloud_sql_instances: quiosquemassagem:southamerica-east1:quiosquemassagem